# Full regularization sweep analyzer

Compare A recovery and control in abundant and single-shot.

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
pd.set_option("display.max_columns", 240)
pd.set_option("display.width", 340)

def find_repo_root(start=None):
    start = Path.cwd() if start is None else Path(start)
    for candidate in [start, *start.parents]:
        if (candidate / "opinion_dynamics").exists():
            return candidate
    raise RuntimeError("Could not find repository root.")

REPO_ROOT = find_repo_root()
RESULTS_ROOT = REPO_ROOT / "opinion_dynamics" / "experiments" / "results"
SS_DIR = RESULTS_ROOT / "experiment_2026_09_29_single_shot_full_regularization_sweep"
AB_DIR = RESULTS_ROOT / "experiment_2026_09_29_abundant_full_regularization_sweep"
OUT_DIR = RESULTS_ROOT / "full_regularization_sweep_analysis_2026_09_29"
OUT_DIR.mkdir(parents=True, exist_ok=True)

SS_PATH = SS_DIR / "single_shot_full_regularization_sweep_seed0.csv"
AB_PATH = AB_DIR / "regularization_sweep_all_runs.csv"
for p in [SS_PATH, AB_PATH]:
    if not p.exists(): raise FileNotFoundError(p)
print("Repo:", REPO_ROOT)

Repo: d:\Work\repos\RL\unknown_graph_networks

C:\Users\Chainsword\AppData\Local\Temp\ipykernel_99460\221622189.py:3: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
ss = pd.read_csv(SS_PATH)
ab = pd.read_csv(AB_PATH)

ss_can = ss.rename(columns={
    "final_mean": "control",
    "final_fit_model_over_identity": "prediction_ratio",
}).copy()
ss_can["regime"] = "single_shot"

ab_can = ab.rename(columns={
    "mean_end": "control",
    "model_over_identity": "prediction_ratio",
}).copy()
ab_can["regime"] = "abundant"

metrics = [
    "control", "prediction_ratio", "A_MAE", "A_Fro", "row_TV",
    "true_edge_mass", "support_topdegree_recall", "edge_AP",
    "centrality_L1", "row_entropy_norm", "effective_neighbors",
]
keep = [
    "regime", "environment_id", "scenario_class", "family", "dynamics",
    "regularizer_kind", "regularizer_lambda", *metrics,
]
work = pd.concat([ss_can[keep], ab_can[keep]], ignore_index=True)

counts = work.groupby(["regime","regularizer_kind","regularizer_lambda"]).size()
assert counts.eq(195).all(), counts[counts != 195]
print("Validated all conditions at 195 environments each.")
display(counts.rename("n").reset_index())

Validated all conditions at 195 environments each.

         regime regularizer_kind  regularizer_lambda    n
0      abundant          entropy        1.000000e-08  195
1      abundant          entropy        1.000000e-07  195
2      abundant          entropy        3.000000e-07  195
3      abundant          entropy        1.000000e-06  195
4      abundant          entropy        3.000000e-06  195
5      abundant          entropy        1.000000e-05  195
6      abundant          entropy        3.000000e-05  195
7      abundant          entropy        1.000000e-04  195
8      abundant          entropy        3.000000e-04  195
9      abundant          entropy        1.000000e-03  195
10     abundant             gini        1.000000e-08  195
11     abundant             gini        1.000000e-07  195
12     abundant             gini        3.000000e-07  195
13     abundant             gini        1.000000e-06  195
14     abundant             gini        3.000000e-06  195
15     abundant             gini        1.000000e-05  195
16     abundant             gini        3.000000e-05  195
17     abundant             gini        1.000000e-04  195
18     abundant             gini        3.000000e-04  195
19     abundant             gini        1.000000e-03  195
20     abundant             none        0.000000e+00  195
21     abundant         theta_l2        1.000000e-10  195
22     abundant         theta_l2        1.000000e-09  195
23     abundant         theta_l2        1.000000e-08  195
24     abundant         theta_l2        1.000000e-07  195
25     abundant         theta_l2        3.000000e-07  195
26     abundant         theta_l2        1.000000e-06  195
27     abundant         theta_l2        3.000000e-06  195
28     abundant         theta_l2        1.000000e-05  195
29     abundant         theta_l2        1.000000e-04  195
30  single_shot          entropy        1.000000e-08  195
31  single_shot          entropy        1.000000e-07  195
32  single_shot          entropy        3.000000e-07  195
33  single_shot          entropy        1.000000e-06  195
34  single_shot          entropy        3.000000e-06  195
35  single_shot          entropy        1.000000e-05  195
36  single_shot          entropy        3.000000e-05  195
37  single_shot          entropy        1.000000e-04  195
38  single_shot          entropy        3.000000e-04  195
39  single_shot          entropy        1.000000e-03  195
40  single_shot             gini        1.000000e-08  195
41  single_shot             gini        1.000000e-07  195
42  single_shot             gini        3.000000e-07  195
43  single_shot             gini        1.000000e-06  195
44  single_shot             gini        3.000000e-06  195
45  single_shot             gini        1.000000e-05  195
46  single_shot             gini        3.000000e-05  195
47  single_shot             gini        1.000000e-04  195
48  single_shot             gini        3.000000e-04  195
49  single_shot             gini        1.000000e-03  195
50  single_shot             none        0.000000e+00  195
51  single_shot         theta_l2        1.000000e-10  195
52  single_shot         theta_l2        1.000000e-09  195
53  single_shot         theta_l2        1.000000e-08  195
54  single_shot         theta_l2        1.000000e-07  195
55  single_shot         theta_l2        3.000000e-07  195
56  single_shot         theta_l2        1.000000e-06  195
57  single_shot         theta_l2        3.000000e-06  195
58  single_shot         theta_l2        1.000000e-05  195
59  single_shot         theta_l2        1.000000e-04  195

In [3]:
refs = (
    work[(work["regularizer_kind"] == "none") & (work["regularizer_lambda"] == 0.0)]
    .set_index(["regime","environment_id"])
)
assert len(refs) == 390

for metric in metrics:
    work[f"delta_{metric}"] = work.apply(
        lambda r: float(r[metric]) - float(refs.loc[(r["regime"],r["environment_id"]), metric]),
        axis=1,
    )

summary = (
    work.groupby(["regime","regularizer_kind","regularizer_lambda"], as_index=False)
    .agg(
        n=("environment_id","size"),
        control=("control","mean"),
        delta_control=("delta_control","mean"),
        prediction_ratio=("prediction_ratio","mean"),
        delta_prediction=("delta_prediction_ratio","mean"),
        A_MAE=("A_MAE","mean"),
        delta_A_MAE=("delta_A_MAE","mean"),
        row_TV=("row_TV","mean"),
        delta_row_TV=("delta_row_TV","mean"),
        true_edge_mass=("true_edge_mass","mean"),
        delta_true_edge_mass=("delta_true_edge_mass","mean"),
        edge_AP=("edge_AP","mean"),
        delta_edge_AP=("delta_edge_AP","mean"),
        centrality_L1=("centrality_L1","mean"),
        delta_centrality_L1=("delta_centrality_L1","mean"),
        row_entropy_norm=("row_entropy_norm","mean"),
        delta_row_entropy=("delta_row_entropy_norm","mean"),
        effective_neighbors=("effective_neighbors","mean"),
        delta_effective_neighbors=("delta_effective_neighbors","mean"),
    )
)

by_dyn = (
    work.groupby(["regime","regularizer_kind","regularizer_lambda","scenario_class","dynamics"], as_index=False)
    .agg(
        n=("environment_id","size"),
        delta_control=("delta_control","mean"),
        delta_prediction=("delta_prediction_ratio","mean"),
        delta_row_TV=("delta_row_TV","mean"),
        delta_true_edge_mass=("delta_true_edge_mass","mean"),
        delta_edge_AP=("delta_edge_AP","mean"),
        delta_centrality_L1=("delta_centrality_L1","mean"),
        delta_effective_neighbors=("delta_effective_neighbors","mean"),
    )
)

worst = (
    by_dyn.groupby(["regime","regularizer_kind","regularizer_lambda"], as_index=False)
    .agg(
        worst_dynamic_control_delta=("delta_control","min"),
        worst_dynamic_row_TV_delta=("delta_row_TV","max"),
        worst_dynamic_prediction_delta=("delta_prediction","max"),
    )
)
summary = summary.merge(worst, on=["regime","regularizer_kind","regularizer_lambda"], how="left")
summary.to_csv(OUT_DIR / "full_regularization_summary.csv", index=False)
by_dyn.to_csv(OUT_DIR / "full_regularization_by_dynamics.csv", index=False)
display(summary.round(6))

,regime,regularizer_kind,regularizer_lambda,n,control,delta_control,prediction_ratio,delta_prediction,A_MAE,delta_A_MAE,row_TV,delta_row_TV,true_edge_mass,delta_true_edge_mass,edge_AP,delta_edge_AP,centrality_L1,delta_centrality_L1,row_entropy_norm,delta_row_entropy,effective_neighbors,delta_effective_neighbors,worst_dynamic_control_delta,worst_dynamic_row_TV_delta,worst_dynamic_prediction_delta
0,abundant,entropy,0.000000,195,0.768628,0.000000,0.638309,-0.000001,0.076799,-0.000000,0.575995,-0.000002,0.433525,0.000002,0.741847,-0.000000,0.480079,-0.000002,0.903401,-0.000002,9.154730,-0.000097,0.000000,0.000000,-0.000000
1,abundant,entropy,0.000000,195,0.768635,0.000007,0.638302,-0.000008,0.076797,-0.000002,0.575979,-0.000017,0.433543,0.000020,0.741846,-0.000001,0.480061,-0.000020,0.903381,-0.000022,9.153857,-0.000970,0.000000,0.000002,-0.000000
2,abundant,entropy,0.000000,195,0.768664,0.000036,0.638285,-0.000025,0.076793,-0.000007,0.575944,-0.000052,0.433582,0.000059,0.741844,-0.000003,0.480021,-0.000060,0.903338,-0.000065,9.151914,-0.002912,0.000000,0.000005,-0.000000
3,abundant,entropy,0.000001,195,0.768662,0.000034,0.638227,-0.000084,0.076776,-0.000023,0.575823,-0.000173,0.433720,0.000197,0.741728,-0.000120,0.479880,-0.000201,0.903186,-0.000217,9.145097,-0.009730,-0.000000,0.000016,-0.000001
4,abundant,entropy,0.000003,195,0.768531,-0.000097,0.638060,-0.000250,0.076731,-0.000069,0.575479,-0.000517,0.434112,0.000589,0.741432,-0.000415,0.479479,-0.000602,0.902748,-0.000655,9.125453,-0.029374,-0.000839,0.000051,-0.000002
5,abundant,entropy,0.000010,195,0.768169,-0.000458,0.637492,-0.000818,0.076574,-0.000225,0.574308,-0.001688,0.435473,0.001950,0.740164,-0.001683,0.478098,-0.001984,0.901170,-0.002233,9.054728,-0.100099,-0.003301,0.000195,-0.000005
6,abundant,entropy,0.000030,195,0.768182,-0.000445,0.635996,-0.002315,0.076171,-0.000628,0.571285,-0.004711,0.439201,0.005678,0.735306,-0.006541,0.474317,-0.005764,0.896265,-0.007138,8.835373,-0.319453,-0.005754,0.000730,0.000000
7,abundant,entropy,0.000100,195,0.765836,-0.002792,0.633075,-0.005236,0.075481,-0.001318,0.566109,-0.009887,0.448689,0.015165,0.712357,-0.029491,0.465901,-0.014180,0.874409,-0.028994,7.925858,-1.228968,-0.018908,0.004546,0.000300
8,abundant,entropy,0.000300,195,0.760158,-0.008469,0.641671,0.003361,0.077577,0.000778,0.581831,0.005834,0.445209,0.011686,0.643862,-0.097985,0.478249,-0.001832,0.813164,-0.090239,6.282098,-2.872729,-0.026891,0.041250,0.035173
9,abundant,entropy,0.001000,195,0.745212,-0.023416,0.689548,0.051238,0.087360,0.010561,0.655201,0.079204,0.381751,-0.051773,0.488856,-0.252991,0.536793,0.056711,0.750924,-0.152479,5.462997,-3.691830,-0.087144,0.239625,0.200007
10,abundant,gini,0.000000,195,0.768628,0.000000,0.638310,-0.000000,0.076799,-0.000000,0.575995,-0.000001,0.433524,0.000001,0.741847,-0.000000,0.480080,-0.000001,0.903402,-0.000001,9.154778,-0.000048,0.000000,0.000000,0.000000
11,abundant,gini,0.000000,195,0.768631,0.000003,0.638305,-0.000005,0.076798,-0.000001,0.575986,-0.000010,0.433534,0.000011,0.741844,-0.000004,0.480070,-0.000011,0.903392,-0.000011,9.154344,-0.000483,0.000000,0.000001,-0.000000
12,abundant,gini,0.000000,195,0.768630,0.000003,0.638296,-0.000014,0.076796,-0.000004,0.575966,-0.000030,0.433556,0.000033,0.741853,0.000005,0.480048,-0.000033,0.903370,-0.000033,9.153377,-0.001449,-0.000013,0.000003,-0.000000
13,abundant,gini,0.000001,195,0.768670,0.000042,0.638264,-0.000047,0.076786,-0.000013,0.575897,-0.000099,0.433634,0.000111,0.741801,-0.000046,0.479972,-0.000110,0.903293,-0.000110,9.149989,-0.004837,0.000000,0.000008,-0.000000
14,abundant,gini,0.000003,195,0.768666,0.000038,0.638171,-0.000140,0.076760,-0.000040,0.575699,-0.000297,0.433856,0.000332,0.741661,-0.000186,0.479752,-0.000329,0.903073,-0.000330,9.140263,-0.014564,-0.000000,0.000025,-0.000001
15,abundant,gini,0.000010,195,0.768369,-0.000259,0.637848,-0.000463,0.076668,-0.000131,0.575011,-0.000985,0.434631,0.001108,0.741016,-0.000832,0.478988,-0.001094,0.902289,-0.001114,9.105655,-0.049171,-0.003006,0.000093,-0.000002
16,abundant,gini,0.000030,195,0.768263,-0.000365,0.636948,-0.001362,0.076413,-0.000386,0.573100,-0.002896,0.436841,0.003318,0.738900,-0.002947,0.476815,-0.003266,0.899942,-0.003461,9.001588,-0.153239,-0.005351,0.000326,-0.000002
17,abundant,gini,0.000100,195,0.767630,-0.000998,0.634230,-0.004080,0.075662,-0.001138,0.567461,-0.008535,0.444259,0.010735,0.728919,-0.012928,0.469769,-0.010313,0.890150,-0.013253,8.562281,-0.592546,-0.008300,0.001730,0.000074
18,abundant,gini,0.000300,195,0.762850,-0.005777,0.634239,-0.004071,0.075485,-0.001315,0.566136,-0.009861,0.455923,0.022400,0.691060,-0.050788,0.466063,-0.014019,0.847188,-0.056215,6.950691,-2.204136,-0.016803,0.012098,0.004339
19,abundant,gini,0.001000,195,0.742246,-0.026381,0.673727,0.035417,0.082863,0.006063,0.621469,0.045473,0.421752,-0.011771,0.568302,-0.173546,0.534506,0.054425,0.736960,-0.166443,4.868804,-4.286022,-0.104007,0.215443,0.201592
20,abundant,none,0.000000,195,0.768628,0.000000,0.638310,0.000000,0.076800,0.000000,0.575996,0.000000,0.433523,0.000000,0.741848,0.000000,0.480081,0.000000,0.903403,0.000000,9.154827,0.000000,0.000000,0.000000,0.000000
21,abundant,theta_l2,0.000000,195,0.768593,-0.000034,0.638320,0.000010,0.076802,0.000003,0.576016,0.000019,0.433502,-0.000021,0.741854,0.000006,0.480104,0.000022,0.903428,0.000025,9.155867,0.001041,-0.000339,0.000062,0.000037
22,abundant,theta_l2,0.000000,195,0.768612,-0.000015,0.638413,0.000102,0.076825,0.000026,0.576189,0.000193,0.433310,-0.000213,0.741891,0.000044,0.480303,0.000222,0.903651,0.000249,9.165203,0.010377,-0.000223,0.000619,0.000373
23,abundant,theta_l2,0.000000,195,0.768651,0.000024,0.639353,0.001043,0.077060,0.000260,0.577947,0.001950,0.431380,-0.002143,0.742797,0.000949,0.482305,0.002224,0.905800,0.002397,9.255433,0.100607,-0.000561,0.006301,0.003829
24,abundant,theta_l2,0.000000,195,0.768238,-0.000390,0.648750,0.010440,0.079219,0.002420,0.594144,0.018148,0.414222,-0.019301,0.746367,0.004520,0.499648,0.019567,0.920453,0.017050,9.876585,0.721759,-0.003403,0.058650,0.038514
25,abundant,theta_l2,0.000000,195,0.764112,-0.004515,0.663860,0.025550,0.082434,0.005634,0.618252,0.042256,0.389249,-0.044275,0.744160,0.002313,0.523261,0.043180,0.935791,0.032388,10.528592,1.373765,-0.024017,0.128957,0.086817
26,abundant,theta_l2,0.000001,195,0.756752,-0.011875,0.690908,0.052597,0.088346,0.011546,0.662595,0.086598,0.343920,-0.089604,0.726709,-0.015139,0.563649,0.083568,0.957586,0.054183,11.580061,2.425235,-0.047465,0.224259,0.149276
27,abundant,theta_l2,0.000003,195,0.750200,-0.018428,0.716749,0.078439,0.094492,0.017693,0.708693,0.132697,0.297405,-0.136118,0.695608,-0.046239,0.605761,0.125679,0.975383,0.071980,12.597316,3.442490,-0.076093,0.266228,0.177929
28,abundant,theta_l2,0.000010,195,0.738035,-0.030592,0.736309,0.097999,0.098572,0.021772,0.739289,0.163293,0.266699,-0.166824,0.632299,-0.109549,0.634727,0.154645,0.986562,0.083159,13.126643,3.971816,-0.111415,0.305645,0.185503
29,abundant,theta_l2,0.000100,195,0.693724,-0.074903,0.770605,0.132295,0.103950,0.027151,0.779628,0.203632,0.226349,-0.207174,0.422699,-0.319149,0.676551,0.196470,0.999690,0.096287,13.975668,4.820841,-0.147481,0.318408,0.284384
30,single_shot,entropy,0.000000,195,0.763149,0.000028,0.171636,-0.000107,0.051167,0.000039,0.383752,0.000294,0.656834,-0.000081,0.704350,-0.000173,0.502514,0.000512,0.548268,-0.000433,3.872423,-0.006331,-0.000154,0.002125,0.000798
31,single_shot,entropy,0.000000,195,0.763182,0.000061,0.172557,0.000814,0.051296,0.000168,0.384722,0.001264,0.656529,-0.000386,0.702580,-0.001943,0.506191,0.004188,0.544460,-0.004241,3.817969,-0.060786,-0.000646,0.012806,0.006092
32,single_shot,entropy,0.000000,195,0.763067,-0.000054,0.174288,0.002545,0.051534,0.000407,0.386508,0.003050,0.657120,0.000205,0.699448,-0.005074,0.510717,0.008715,0.532864,-0.015837,3.698959,-0.179795,-0.002983,0.031242,0.022624
33,single_shot,entropy,0.000001,195,0.762967,-0.000154,0.179171,0.007427,0.052469,0.001341,0.393517,0.010059,0.660122,0.003207,0.690129,-0.014394,0.533357,0.031355,0.489626,-0.059075,3.300427,-0.578327,-0.003596,0.072631,0.056167
34,single_shot,entropy,0.000003,195,0.761330,-0.001791,0.197465,0.025722,0.054183,0.003055,0.406371,0.022913,0.677192,0.020277,0.669294,-0.035228,0.607204,0.105202,0.387630,-0.161072,2.637455,-1.241300,-0.012566,0.119244,0.106401
35,single_shot,entropy,0.000010,195,0.755503,-0.007618,0.249508,0.077765,0.058877,0.007749,0.441576,0.058118,0.681594,0.024679,0.626444,-0.078079,0.726852,0.224850,0.256954,-0.291747,1.998742,-1.880013,-0.028787,0.227242,0.235033
36,single_shot,entropy,0.000030,195,0.740241,-0.022879,0.326531,0.154788,0.067635,0.016507,0.507261,0.123803,0.647113,-0.009802,0.559719,-0.144803,0.859739,0.357737,0.176227,-0.372474,1.661864,-2.216890,-0.049566,0.266339,0.338266
37,single_shot,entropy,0.000100,195,0.718864,-0.044256,0.466996,0.295252,0.082213,0.031085,0.616597,0.233139,0.583680,-0.073235,0.485260,-0.219263,1.063236,0.561233,0.090299,-0.458402,1.321163,-2.557591,-0.161463,0.556562,0.711735
38,single_shot,entropy,0.000300,195,0.696579,-0.066542,0.557268,0.385525,0.092488,0.041360,0.693659,0.310200,0.528044,-0.128871,0.433822,-0.270701,1.231129,0.729127,0.044883,-0.503818,1.160917,-2.717837,-0.223392,0.708968,0.847571
39,single_shot,entropy,0.001000,195,0.680363,-0.082758,0.625235,0.453492,0.102786,0.051658,0.770892,0.387434,0.456779,-0.200136,0.386684,-0.317838,1.375391,0.873389,0.015550,-0.533151,1.051650,-2.827104,-0.250773,0.807101,0.913994
40,single_shot,gini,0.000000,195,0.763181,0.000060,0.171855,0.000112,0.051177,0.000049,0.383829,0.000371,0.656808,-0.000107,0.704328,-0.000195,0.502581,0.000578,0.548387,-0.000315,3.874478,-0.004277,0.000000,0.003331,0.001087
41,single_shot,gini,0.000000,195,0.763299,0.000179,0.171897,0.000154,0.051327,0.000200,0.384954,0.001496,0.656332,-0.000583,0.702649,-0.001873,0.505722,0.003720,0.544814,-0.003887,3.830346,-0.048409,-0.000372,0.012791,0.001569
42,single_shot,gini,0.000000,195,0.763045,-0.000075,0.175075,0.003332,0.051412,0.000284,0.385587,0.002129,0.658503,0.001588,0.700938,-0.003585,0.511954,0.009952,0.533022,-0.015680,3.715837,-0.162917,-0.002217,0.027765,0.025951
43,single_shot,gini,0.000001,195,0.762683,-0.000437,0.178234,0.006491,0.052484,0.001357,0.393633,0.010175,0.661612,0.004698,0.694185,-0.010338,0.536644,0.034642,0.494509,-0.054192,3.375020,-0.503735,-0.004419,0.063477,0.040329
44,single_shot,gini,0.000003,195,0.760911,-0.002209,0.200492,0.028748,0.054939,0.003812,0.412045,0.028587,0.672133,0.015218,0.671978,-0.032544,0.603604,0.101602,0.397190,-0.151511,2.749031,-1.129723,-0.013244,0.109603,0.124539
45,single_shot,gini,0.000010,195,0.755084,-0.008036,0.259979,0.088235,0.060473,0.009345,0.453546,0.070088,0.672588,0.015673,0.622500,-0.082023,0.741855,0.239852,0.261194,-0.287508,2.008402,-1.870352,-0.025861,0.236152,0.282586
46,single_shot,gini,0.000030,195,0.739863,-0.023257,0.343408,0.171664,0.070198,0.019070,0.526487,0.143029,0.654884,-0.002031,0.556109,-0.148413,0.919967,0.417964,0.149255,-0.399446,1.535857,-2.342897,-0.044957,0.286304,0.347238
47,single_shot,gini,0.000100,195,0.713234,-0.049886,0.509516,0.337772,0.086475,0.035348,0.648565,0.265107,0.579187,-0.077728,0.474102,-0.230420,1.111089,0.609086,0.068921,-0.479780,1.229862,-2.648892,-0.159192,0.594898,0.744660
48,single_shot,gini,0.000300,195,0.696098,-0.067022,0.580422,0.408679,0.096323,0.045195,0.722420,0.338962,0.526928,-0.129987,0.427117,-0.277406,1.251183,0.749180,0.030558,-0.518143,1.094317,-2.784437,-0.220616,0.719757,0.888427
49,single_shot,gini,0.001000,195,0.681874,-0.081247,0.640969,0.469226,0.104557,0.053429,0.784178,0.400720,0.469348,-0.187567,0.386135,-0.318388,1.361437,0.859434,0.007106,-0.541595,1.019164,-2.859591,-0.213491,0.746319,0.884075
50,single_shot,none,0.000000,195,0.763121,0.000000,0.171743,0.000000,0.051128,0.000000,0.383458,0.000000,0.656915,0.000000,0.704522,0.000000,0.502002,0.000000,0.548701,0.000000,3.878754,0.000000,0.000000,0.000000,0.000000
51,single_shot,theta_l2,0.000000,195,0.763421,0.000300,0.171703,-0.000041,0.051218,0.000090,0.384133,0.000675,0.655654,-0.001261,0.705270,0.000748,0.504582,0.002579,0.553974,0.005273,3.914406,0.035652,-0.000821,0.002923,0.001102
52,single_shot,theta_l2,0.000000,195,0.764104,0.000983,0.173766,0.002023,0.051337,0.000209,0.385027,0.001569,0.650540,-0.006375,0.716506,0.011984,0.484816,-0.017186,0.582308,0.033607,4.164579,0.285824,-0.001196,0.010055,0.009701
53,single_shot,theta_l2,0.000000,195,0.761048,-0.002073,0.201519,0.029776,0.056934,0.005806,0.427002,0.043544,0.601697,-0.055218,0.704844,0.000322,0.482177,-0.019825,0.663640,0.114939,5.221324,1.342570,-0.005822,0.097223,0.065128
54,single_shot,theta_l2,0.000000,195,0.741814,-0.021307,0.346237,0.174493,0.076683,0.025555,0.575122,0.191664,0.444957,-0.211958,0.593107,-0.111415,0.526740,0.024738,0.831750,0.283049,8.395507,4.516752,-0.067868,0.327766,0.452515
55,single_shot,theta_l2,0.000000,195,0.726144,-0.036976,0.438959,0.267215,0.086531,0.035404,0.648986,0.265528,0.364620,-0.292295,0.521789,-0.182733,0.564256,0.062253,0.902796,0.354095,10.263214,6.384460,-0.136002,0.479376,0.799652
56,single_shot,theta_l2,0.000001,195,0.715382,-0.047739,0.503859,0.332115,0.095019,0.043891,0.712640,0.329182,0.298198,-0.358717,0.463467,-0.241056,0.608813,0.106810,0.954546,0.405845,11.941695,8.062941,-0.158787,0.634843,0.853893
57,single_shot,theta_l2,0.000003,195,0.703672,-0.059449,0.548572,0.376828,0.099495,0.048368,0.746215,0.362757,0.263836,-0.393079,0.424350,-0.280173,0.627010,0.125007,0.978176,0.429474,12.869265,8.990511,-0.187010,0.640884,0.860428
58,single_shot,theta_l2,0.000010,195,0.698829,-0.064292,0.596749,0.425006,0.102429,0.051302,0.768219,0.384761,0.241067,-0.415848,0.399925,-0.304597,0.642463,0.140460,0.991646,0.442945,13.538815,9.660060,-0.210526,0.641959,0.891582
59,single_shot,theta_l2,0.000100,195,0.676478,-0.086643,0.644159,0.472415,0.104431,0.053303,0.783231,0.399773,0.222732,-0.434182,0.396930,-0.307592,0.679595,0.177592,0.999936,0.451235,13.995159,10.116405,-0.238323,0.642317,0.864200

In [4]:
metrics_wide = [
    "delta_control", "delta_prediction", "delta_A_MAE", "delta_row_TV",
    "delta_true_edge_mass", "delta_edge_AP", "delta_centrality_L1",
    "delta_effective_neighbors", "worst_dynamic_control_delta",
    "worst_dynamic_row_TV_delta",
]
parts=[]
for regime in ["abundant","single_shot"]:
    p = summary[summary["regime"] == regime][
        ["regularizer_kind","regularizer_lambda", *metrics_wide]
    ].copy()
    p = p.rename(columns={c:f"{regime}_{c}" for c in metrics_wide})
    parts.append(p)
joint = parts[0].merge(parts[1], on=["regularizer_kind","regularizer_lambda"], validate="one_to_one")
joint = joint.sort_values(["regularizer_kind","regularizer_lambda"])
joint.to_csv(OUT_DIR / "full_regularization_joint_side_by_side.csv", index=False)
print("Deltas versus no regularization")
display(joint.round(6))

Deltas versus no regularization

,regularizer_kind,regularizer_lambda,abundant_delta_control,abundant_delta_prediction,abundant_delta_A_MAE,abundant_delta_row_TV,abundant_delta_true_edge_mass,abundant_delta_edge_AP,abundant_delta_centrality_L1,abundant_delta_effective_neighbors,abundant_worst_dynamic_control_delta,abundant_worst_dynamic_row_TV_delta,single_shot_delta_control,single_shot_delta_prediction,single_shot_delta_A_MAE,single_shot_delta_row_TV,single_shot_delta_true_edge_mass,single_shot_delta_edge_AP,single_shot_delta_centrality_L1,single_shot_delta_effective_neighbors,single_shot_worst_dynamic_control_delta,single_shot_worst_dynamic_row_TV_delta
0,entropy,0.000000,0.000000,-0.000001,-0.000000,-0.000002,0.000002,-0.000000,-0.000002,-0.000097,0.000000,0.000000,0.000028,-0.000107,0.000039,0.000294,-0.000081,-0.000173,0.000512,-0.006331,-0.000154,0.002125
1,entropy,0.000000,0.000007,-0.000008,-0.000002,-0.000017,0.000020,-0.000001,-0.000020,-0.000970,0.000000,0.000002,0.000061,0.000814,0.000168,0.001264,-0.000386,-0.001943,0.004188,-0.060786,-0.000646,0.012806
2,entropy,0.000000,0.000036,-0.000025,-0.000007,-0.000052,0.000059,-0.000003,-0.000060,-0.002912,0.000000,0.000005,-0.000054,0.002545,0.000407,0.003050,0.000205,-0.005074,0.008715,-0.179795,-0.002983,0.031242
3,entropy,0.000001,0.000034,-0.000084,-0.000023,-0.000173,0.000197,-0.000120,-0.000201,-0.009730,-0.000000,0.000016,-0.000154,0.007427,0.001341,0.010059,0.003207,-0.014394,0.031355,-0.578327,-0.003596,0.072631
4,entropy,0.000003,-0.000097,-0.000250,-0.000069,-0.000517,0.000589,-0.000415,-0.000602,-0.029374,-0.000839,0.000051,-0.001791,0.025722,0.003055,0.022913,0.020277,-0.035228,0.105202,-1.241300,-0.012566,0.119244
5,entropy,0.000010,-0.000458,-0.000818,-0.000225,-0.001688,0.001950,-0.001683,-0.001984,-0.100099,-0.003301,0.000195,-0.007618,0.077765,0.007749,0.058118,0.024679,-0.078079,0.224850,-1.880013,-0.028787,0.227242
6,entropy,0.000030,-0.000445,-0.002315,-0.000628,-0.004711,0.005678,-0.006541,-0.005764,-0.319453,-0.005754,0.000730,-0.022879,0.154788,0.016507,0.123803,-0.009802,-0.144803,0.357737,-2.216890,-0.049566,0.266339
7,entropy,0.000100,-0.002792,-0.005236,-0.001318,-0.009887,0.015165,-0.029491,-0.014180,-1.228968,-0.018908,0.004546,-0.044256,0.295252,0.031085,0.233139,-0.073235,-0.219263,0.561233,-2.557591,-0.161463,0.556562
8,entropy,0.000300,-0.008469,0.003361,0.000778,0.005834,0.011686,-0.097985,-0.001832,-2.872729,-0.026891,0.041250,-0.066542,0.385525,0.041360,0.310200,-0.128871,-0.270701,0.729127,-2.717837,-0.223392,0.708968
9,entropy,0.001000,-0.023416,0.051238,0.010561,0.079204,-0.051773,-0.252991,0.056711,-3.691830,-0.087144,0.239625,-0.082758,0.453492,0.051658,0.387434,-0.200136,-0.317838,0.873389,-2.827104,-0.250773,0.807101
10,gini,0.000000,0.000000,-0.000000,-0.000000,-0.000001,0.000001,-0.000000,-0.000001,-0.000048,0.000000,0.000000,0.000060,0.000112,0.000049,0.000371,-0.000107,-0.000195,0.000578,-0.004277,0.000000,0.003331
11,gini,0.000000,0.000003,-0.000005,-0.000001,-0.000010,0.000011,-0.000004,-0.000011,-0.000483,0.000000,0.000001,0.000179,0.000154,0.000200,0.001496,-0.000583,-0.001873,0.003720,-0.048409,-0.000372,0.012791
12,gini,0.000000,0.000003,-0.000014,-0.000004,-0.000030,0.000033,0.000005,-0.000033,-0.001449,-0.000013,0.000003,-0.000075,0.003332,0.000284,0.002129,0.001588,-0.003585,0.009952,-0.162917,-0.002217,0.027765
13,gini,0.000001,0.000042,-0.000047,-0.000013,-0.000099,0.000111,-0.000046,-0.000110,-0.004837,0.000000,0.000008,-0.000437,0.006491,0.001357,0.010175,0.004698,-0.010338,0.034642,-0.503735,-0.004419,0.063477
14,gini,0.000003,0.000038,-0.000140,-0.000040,-0.000297,0.000332,-0.000186,-0.000329,-0.014564,-0.000000,0.000025,-0.002209,0.028748,0.003812,0.028587,0.015218,-0.032544,0.101602,-1.129723,-0.013244,0.109603
15,gini,0.000010,-0.000259,-0.000463,-0.000131,-0.000985,0.001108,-0.000832,-0.001094,-0.049171,-0.003006,0.000093,-0.008036,0.088235,0.009345,0.070088,0.015673,-0.082023,0.239852,-1.870352,-0.025861,0.236152
16,gini,0.000030,-0.000365,-0.001362,-0.000386,-0.002896,0.003318,-0.002947,-0.003266,-0.153239,-0.005351,0.000326,-0.023257,0.171664,0.019070,0.143029,-0.002031,-0.148413,0.417964,-2.342897,-0.044957,0.286304
17,gini,0.000100,-0.000998,-0.004080,-0.001138,-0.008535,0.010735,-0.012928,-0.010313,-0.592546,-0.008300,0.001730,-0.049886,0.337772,0.035348,0.265107,-0.077728,-0.230420,0.609086,-2.648892,-0.159192,0.594898
18,gini,0.000300,-0.005777,-0.004071,-0.001315,-0.009861,0.022400,-0.050788,-0.014019,-2.204136,-0.016803,0.012098,-0.067022,0.408679,0.045195,0.338962,-0.129987,-0.277406,0.749180,-2.784437,-0.220616,0.719757
19,gini,0.001000,-0.026381,0.035417,0.006063,0.045473,-0.011771,-0.173546,0.054425,-4.286022,-0.104007,0.215443,-0.081247,0.469226,0.053429,0.400720,-0.187567,-0.318388,0.859434,-2.859591,-0.213491,0.746319
20,none,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,theta_l2,0.000000,-0.000034,0.000010,0.000003,0.000019,-0.000021,0.000006,0.000022,0.001041,-0.000339,0.000062,0.000300,-0.000041,0.000090,0.000675,-0.001261,0.000748,0.002579,0.035652,-0.000821,0.002923
22,theta_l2,0.000000,-0.000015,0.000102,0.000026,0.000193,-0.000213,0.000044,0.000222,0.010377,-0.000223,0.000619,0.000983,0.002023,0.000209,0.001569,-0.006375,0.011984,-0.017186,0.285824,-0.001196,0.010055
23,theta_l2,0.000000,0.000024,0.001043,0.000260,0.001950,-0.002143,0.000949,0.002224,0.100607,-0.000561,0.006301,-0.002073,0.029776,0.005806,0.043544,-0.055218,0.000322,-0.019825,1.342570,-0.005822,0.097223
24,theta_l2,0.000000,-0.000390,0.010440,0.002420,0.018148,-0.019301,0.004520,0.019567,0.721759,-0.003403,0.058650,-0.021307,0.174493,0.025555,0.191664,-0.211958,-0.111415,0.024738,4.516752,-0.067868,0.327766
25,theta_l2,0.000000,-0.004515,0.025550,0.005634,0.042256,-0.044275,0.002313,0.043180,1.373765,-0.024017,0.128957,-0.036976,0.267215,0.035404,0.265528,-0.292295,-0.182733,0.062253,6.384460,-0.136002,0.479376
26,theta_l2,0.000001,-0.011875,0.052597,0.011546,0.086598,-0.089604,-0.015139,0.083568,2.425235,-0.047465,0.224259,-0.047739,0.332115,0.043891,0.329182,-0.358717,-0.241056,0.106810,8.062941,-0.158787,0.634843
27,theta_l2,0.000003,-0.018428,0.078439,0.017693,0.132697,-0.136118,-0.046239,0.125679,3.442490,-0.076093,0.266228,-0.059449,0.376828,0.048368,0.362757,-0.393079,-0.280173,0.125007,8.990511,-0.187010,0.640884
28,theta_l2,0.000010,-0.030592,0.097999,0.021772,0.163293,-0.166824,-0.109549,0.154645,3.971816,-0.111415,0.305645,-0.064292,0.425006,0.051302,0.384761,-0.415848,-0.304597,0.140460,9.660060,-0.210526,0.641959
29,theta_l2,0.000100,-0.074903,0.132295,0.027151,0.203632,-0.207174,-0.319149,0.196470,4.820841,-0.147481,0.318408,-0.086643,0.472415,0.053303,0.399773,-0.434182,-0.307592,0.177592,10.116405,-0.238323,0.642317

In [5]:
MAX_CONTROL_DROP = 0.001
candidates = joint[
    (joint["regularizer_kind"] != "none")
    & (joint["abundant_delta_control"] >= -MAX_CONTROL_DROP)
    & (joint["single_shot_delta_control"] >= -MAX_CONTROL_DROP)
    & (joint["abundant_delta_row_TV"] < 0)
    & (joint["single_shot_delta_row_TV"] < 0)
].copy()

print(f"Candidates with row-TV improvement in both regimes and control drop <= {MAX_CONTROL_DROP:g}:")
display(candidates.round(6))

print("\nDiffusion check (effective neighbors; negative means more concentrated):")
display(joint[[
    "regularizer_kind","regularizer_lambda",
    "abundant_delta_effective_neighbors","single_shot_delta_effective_neighbors",
    "abundant_delta_row_TV","single_shot_delta_row_TV",
    "abundant_delta_control","single_shot_delta_control",
]].round(6))

print("\nOutputs:", OUT_DIR)
print("FULL REGULARIZATION SWEEP ANALYSIS COMPLETE")

Candidates with row-TV improvement in both regimes and control drop <= 0.001:

Empty DataFrame
Columns: [regularizer_kind, regularizer_lambda, abundant_delta_control, abundant_delta_prediction, abundant_delta_A_MAE, abundant_delta_row_TV, abundant_delta_true_edge_mass, abundant_delta_edge_AP, abundant_delta_centrality_L1, abundant_delta_effective_neighbors, abundant_worst_dynamic_control_delta, abundant_worst_dynamic_row_TV_delta, single_shot_delta_control, single_shot_delta_prediction, single_shot_delta_A_MAE, single_shot_delta_row_TV, single_shot_delta_true_edge_mass, single_shot_delta_edge_AP, single_shot_delta_centrality_L1, single_shot_delta_effective_neighbors, single_shot_worst_dynamic_control_delta, single_shot_worst_dynamic_row_TV_delta]
Index: []

Diffusion check (effective neighbors; negative means more concentrated):

   regularizer_kind  regularizer_lambda  abundant_delta_effective_neighbors  single_shot_delta_effective_neighbors  abundant_delta_row_TV  single_shot_delta_row_TV  abundant_delta_control  single_shot_delta_control
0           entropy            0.000000                           -0.000097                              -0.006331              -0.000002                  0.000294                0.000000                   0.000028
1           entropy            0.000000                           -0.000970                              -0.060786              -0.000017                  0.001264                0.000007                   0.000061
2           entropy            0.000000                           -0.002912                              -0.179795              -0.000052                  0.003050                0.000036                  -0.000054
3           entropy            0.000001                           -0.009730                              -0.578327              -0.000173                  0.010059                0.000034                  -0.000154
4           entropy            0.000003                           -0.029374                              -1.241300              -0.000517                  0.022913               -0.000097                  -0.001791
5           entropy            0.000010                           -0.100099                              -1.880013              -0.001688                  0.058118               -0.000458                  -0.007618
6           entropy            0.000030                           -0.319453                              -2.216890              -0.004711                  0.123803               -0.000445                  -0.022879
7           entropy            0.000100                           -1.228968                              -2.557591              -0.009887                  0.233139               -0.002792                  -0.044256
8           entropy            0.000300                           -2.872729                              -2.717837               0.005834                  0.310200               -0.008469                  -0.066542
9           entropy            0.001000                           -3.691830                              -2.827104               0.079204                  0.387434               -0.023416                  -0.082758
10             gini            0.000000                           -0.000048                              -0.004277              -0.000001                  0.000371                0.000000                   0.000060
11             gini            0.000000                           -0.000483                              -0.048409              -0.000010                  0.001496                0.000003                   0.000179
12             gini            0.000000                           -0.001449                              -0.162917              -0.000030                  0.002129                0.000003                  -0.000075
13             gini            0.000001                           -0.004837                              -0.503735              -0.000099                  0.010175                0.000042                  -0.000437
14             gini            0.000003                           -0.014564                              -1.129723              -0.000297                  0.028587                0.000038                  -0.002209
15             gini            0.000010                           -0.049171                              -1.870352              -0.000985                  0.070088               -0.000259                  -0.008036
16             gini            0.000030                           -0.153239                              -2.342897              -0.002896                  0.143029               -0.000365                  -0.023257
17             gini            0.000100                           -0.592546                              -2.648892              -0.008535                  0.265107               -0.000998                  -0.049886
18             gini            0.000300                           -2.204136                              -2.784437              -0.009861                  0.338962               -0.005777                  -0.067022
19             gini            0.001000                           -4.286022                              -2.859591               0.045473                  0.400720               -0.026381                  -0.081247
20             none            0.000000                            0.000000                               0.000000               0.000000                  0.000000                0.000000                   0.000000
21         theta_l2            0.000000                            0.001041                               0.035652               0.000019                  0.000675               -0.000034                   0.000300
22         theta_l2            0.000000                            0.010377                               0.285824               0.000193                  0.001569               -0.000015                   0.000983
23         theta_l2            0.000000                            0.100607                               1.342570               0.001950                  0.043544                0.000024                  -0.002073
24         theta_l2            0.000000                            0.721759                               4.516752               0.018148                  0.191664               -0.000390                  -0.021307
25         theta_l2            0.000000                            1.373765                               6.384460               0.042256                  0.265528               -0.004515                  -0.036976
26         theta_l2            0.000001                            2.425235                               8.062941               0.086598                  0.329182               -0.011875                  -0.047739
27         theta_l2            0.000003                            3.442490                               8.990511               0.132697                  0.362757               -0.018428                  -0.059449
28         theta_l2            0.000010                            3.971816                               9.660060               0.163293                  0.384761               -0.030592                  -0.064292
29         theta_l2            0.000100                            4.820841                              10.116405               0.203632                  0.399773               -0.074903                  -0.086643

Outputs: d:\Work\repos\RL\unknown_graph_networks\opinion_dynamics\experiments\results\full_regularization_sweep_analysis_2026_09_29
FULL REGULARIZATION SWEEP ANALYSIS COMPLETE